OverflowError: Python int too large to convert to C long in despeckle
I had this error while using pyart.correct.despeckle:

 File "/g/data2/rr5/vhl548/short/miniconda3/envs/radar/lib/python3.6/site-packages/pyart/correct/despeckle.py", line 144, in despeckle_field
    gatefilter=gatefilter, delta=delta)
  File "/g/data2/rr5/vhl548/short/miniconda3/envs/radar/lib/python3.6/site-packages/pyart/correct/despeckle.py", line 85, in find_objects
    gatefilter=gatefilter)
  File "/g/data2/rr5/vhl548/short/miniconda3/envs/radar/lib/python3.6/site-packages/pyart/correct/despeckle.py", line 412, in _get_data
    data = data.filled(fill_value=BAD)
  File "/g/data2/rr5/vhl548/short/miniconda3/envs/radar/lib/python3.6/site-packages/numpy/ma/core.py", line 3687, in filled
    fill_value = _check_fill_value(fill_value, self.dtype)
  File "/g/data2/rr5/vhl548/short/miniconda3/envs/radar/lib/python3.6/site-packages/numpy/ma/core.py", line 485, in _check_fill_value
    raise TypeError(err_msg % (fill_value, ndtype))
TypeError: Fill value 1e+20 overflows dtype int16

I don't know why the dtype is int16 (I'm using numpy 1.12 and python 3.6) but that was fixed by changing the global constant BAD to 9999.