ENH: Addition of New Radar Echo Classification Function (#1495)
* ADD: _echo_class_wt.py: RadarEchoClass module with all methods/code from PyREClass.

* ADD:wrapper function for wt_reclass

* REFORMAT: Function names comply with PyART & PEP8 standards.

* REFORMAT: Function names comply with PyART & PEP8 standards.

* Revert "REFORMAT: Function names comply with PyART & PEP8 standards."

This reverts commit 6ce7cc8c711256c1047ff6596e93896a66274ff0.

* REFORMAT: Function names comply with PyART & PEP8 standards.

* ADD: masked array, detailed func arguments

* MOD:func user arguments used,class num changed.

* DOC:function and user arguments.

* MOD: added metadata to field dictinery.

* order of classes changed

* cappi level added;better description of calsses

* REFORMAT: PEP8 style

* FORMAT:PEP8

* MOD:sanity check for conv core threshold

* MOD:More sanity check for thresholds

* MOD:Added override to sanity check+documentation

* MOD:minor

* invalid grid raises exception

* first unit test added

* ADD:func make_gaussian_storm_grid

* ADD: test for  output validity

* ADD:utest for results of classification

* ENH: test documentation and apply black formatting

* ENH:small test func  merged;name change

* ADD: Stat-based tests for Gaussian storm grid function

* ADD: example

* FORMAT:Black

* FIX: issues for #1495 the code review

- aded TypeError handling in `_echo_class_wt.py`
- Left tab docstring in `echo_class.py`
- Added blank line in `_echo_class_wt.py`
- Did not check `reflectivity_to_rainrate` function for duplication
- Spellcheck Done
- Confirmed grid object check in `echo_class.py`
- Added `#noqa` comment in `__init__.py`

* FIX:unused imports andvariables removed

* Removed two line func sum_conv_wavelets();

* minor

* Removed reflectivity_to_rainrate()

* Test PAssed reflectivity_to_rainrate():

* minor:autosummary

* ADD:conv_wavelet_sum()

* Func Renamed: get_reclass -> wavelet_reclas

* Refined documentation and Descriptive user arguments

* FMT: Black

* ENH:Docstring

* DOC:Better description & ordering  of classification categories

* REFACTOR:scale_break now computed in calling function

Moved scale break calculation to calling function, outputting scale_break as a parameter for the user. Adjusted related functions and variables.

* ENH:scale_break is adaptive to resolution

* ENH:atol added, tests default function arguments

* FROMAT:black

* MINOR:corrected tab in docstring

* used new scaling and added description

* MINOR: alignment in docstring

* FORAMT:linting error corrected

* 'LINTING ERR:import-block sorted;extra'()' removed'

Follwing errors are fixed:
pyart/retrieve/_echo_class_wt.py:192:26: UP034 [*] Avoid extraneous parentheses
pyart/retrieve/echo_class.py:6:1: I001 [*] Import block is un-sorted or un-formatted
Found 2 errors.
[*] 2 fixable with the `--fix` option.
Error: Process completed with exit code 1.

* FIX: Fix linting error

* FIX: Fix more linting errors

* DOCS:minor docstrig chages from Zach

* DOCS: testing precommit

---------

Co-authored-by: mgrover1 <mgroverwx@gmail.com>
Co-authored-by: Max Grover <maxi2312@gmail.com>